[project]
name = "verilog2pwl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.3.0",
    "colorlog>=6.9.0",
    "numpy>=2.3.3",
    "pyvcd>=0.4.1",
    "pyverilog>=1.3.0",
    "sympy>=1.14.0",
]
