#!/bin/bash
# Author: Dongrui Hu
# Email: dongruihu@picoheart.com
# Date: 2025/08/20
# Descripton:
#   Dump verilog testbench waveform to VCD (Value Change Dump) format, using VCS

export VCS_VERSION='V-2023.12-1'
export VERDI_VERSION='V-2023.12-SP2-1'

if [ -z "$LSF_QUEUE" ]; then
    echo "Using default LSF queue."
    export LSF_QUEUE='normal'
fi

module load iverilog/12.0
module load vcs/$VCS_VERSION
module load verdi/$VERDI_VERSION

# Launch script
SCRIPT_PATH="$(readlink -f "${BASH_SOURCE[0]}")"
# Get the actual directory of the script
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"

$SCRIPT_DIR/verilog2pwl.py $*